# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/USER/Desktop/Digital_Project/XOR_Stream_Cipher_UART/XOR_Stream_Cipher_UART.cache/wt [current_project]
set_property parent.project_path C:/Users/USER/Desktop/Digital_Project/XOR_Stream_Cipher_UART/XOR_Stream_Cipher_UART.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet C:/Users/USER/Desktop/Digital_Project/XOR_Stream_Cipher_UART/XOR_Stream_Cipher_UART.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp
set_property used_in_implementation false [get_files C:/Users/USER/Desktop/Digital_Project/XOR_Stream_Cipher_UART/XOR_Stream_Cipher_UART.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/USER/Desktop/Digital_Project/XOR_Stream_Cipher_UART/XOR_Stream_Cipher_UART.srcs/sources_1/new/UART_tx.v
  C:/Users/USER/Desktop/Digital_Project/XOR_Stream_Cipher_UART/XOR_Stream_Cipher_UART.srcs/sources_1/new/keybuilder.v
  C:/Users/USER/Desktop/Digital_Project/XOR_Stream_Cipher_UART/XOR_Stream_Cipher_UART.srcs/sources_1/new/UART_rx.v
  C:/Users/USER/Desktop/Digital_Project/XOR_Stream_Cipher_UART/XOR_Stream_Cipher_UART.srcs/sources_1/new/Debounce.v
  C:/Users/USER/Desktop/Digital_Project/XOR_Stream_Cipher_UART/XOR_Stream_Cipher_UART.srcs/sources_1/new/UART_top.v
}
read_xdc C:/Users/USER/Desktop/Digital_Project/XOR_Stream_Cipher_UART/XOR_Stream_Cipher_UART.srcs/constrs_1/new/uart_const.xdc
set_property used_in_implementation false [get_files C:/Users/USER/Desktop/Digital_Project/XOR_Stream_Cipher_UART/XOR_Stream_Cipher_UART.srcs/constrs_1/new/uart_const.xdc]

synth_design -top Top_System -part xc7a35tcpg236-1
write_checkpoint -noxdef Top_System.dcp
catch { report_utilization -file Top_System_utilization_synth.rpt -pb Top_System_utilization_synth.pb }
